services:
  solarplant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/:/app/data/
      - ./config/:/app/config/      
    restart: always
