api:
  address: "0.0.0.0"
  port: 8080
  session_key: ${API_SESSION_KEY}
  admin_user: ${API_ADMIN_USER}
  admin_password: ${API_ADMIN_PASSWORD}

database:
  path: ./data/solarplant.db

ferroamp:
  host: ${FERROAMP_HOST}
  port: 1883
  username: extapi
  password: ${FERROAMP_PASSWORD}

weather_forecast:
  latitude: ${WEATHER_FORECAST_LATITUDE}
  longitude: ${WEATHER_FORECAST_LONGITUDE}
  run_at: "0 */4 * * *"

energy_forecast:
  hours_ahead: 8
  historical_days: 7
  cloud_cover_impact: 0.5
  run_at: "1 */4 * * *"

energy_price:
  tax_including_vat: 0.535
  tax_reduction: 0.6
  grid_benefit: 0.05
  area: SE4
  currency: SEK  
  run_at: "2 */2 * * *"

planner:
  hours_ahead: 8
  run_at: "3 */1 * * *"
  grid_max_power: 25

battery_spec:
  capacity: ${BATTERY_SPEC_CAPACITY}
  min_level: ${BATTERY_SPEC_MIN_LEVEL}
  max_level: ${BATTERY_SPEC_MAX_LEVEL}
  max_charge_rate: ${BATTERY_SPEC_MAX_CHARGE_RATE}
  max_discharge_rate: ${BATTERY_SPEC_MAX_DISCHARGE_RATE}
  degradation_cost: ${BATTERY_SPEC_DEGRADATION_COST}

battery_regulator_strategy:
  interval: 10
  update_threshold: 250

logging:
  db_level: DEBUG
  db_attrs_format: JSON
  db_max_entries: 10000
  console_level: DEBUG

