api:
  address: "0.0.0.0"
  port: 8080
  www_dir: "./www"

database:
  path: ./data/solarplant.db

ferroamp:
  host: ${FERROAMP_HOST}
  port: 1883
  username: extapi
  password: ${FERROAMP_PASSWORD}

weather_forecast:
  latitude: 56.8619418
  longitude: 12.687893
  run_at: "0 */4 * * *"

energy_forecast:
  hours_ahead: 8
  historical_days: 7
  cloud_cover_impact: 0.5
  run_at: "1 */4 * * *"

energy_price:
  tax_including_vat: 0.535
  tax_reduction: 0.6
  grid_benefit: 0.05
  area: SE4
  currency: SEK  
  run_at: "2 */2 * * *"

planner:
  hours_ahead: 8
  run_at: "3 */1 * * *"
  grid_max_power: 25

battery_spec:
  capacity: 14.2
  min_level: 10
  max_level: 100
  max_charge_rate: 7
  max_discharge_rate: 7
  degradation_cost: 0.1

battery_regulator_strategy:
  interval: 10
  update_threshold: 250

